from pathlib import Path

path = Path('/home/ubuntu/Ultimate-3D-Game/index.html')
text = path.read_text()

def replace_between(source, start_marker, end_marker, replacement):
    start = source.index(start_marker)
    end = source.index(end_marker, start)
    return source[:start] + replacement + source[end:]

css = r'''
        /* Phase 6: full-building entry prompts and premium city atmosphere. */
        .building-proximity { display:flex; flex-direction:column; align-items:center; gap:2px; min-width:118px; padding:7px 10px; border:2px solid rgba(255,255,255,.9); border-radius:13px; color:#effaff; background:linear-gradient(145deg,rgba(33,66,39,.94),rgba(20,105,76,.9)); box-shadow:0 6px 0 rgba(0,16,36,.26),0 12px 24px rgba(0,0,0,.24); font:800 10px/1.1 system-ui,sans-serif; text-align:center; letter-spacing:.04em; } .building-proximity b { display:inline-flex; min-width:20px; justify-content:center; padding:3px 5px; border-radius:6px; color:#174632; background:#fff; font-size:11px; } .building-proximity small { color:#d4ffca; font-size:8px; font-weight:800; }
'''
if 'Phase 6: full-building entry prompts' not in text:
    text = text.replace('        </style>', css + '\n        </style>', 1)

text = text.replace("let interiorState = null, interiorGroup = null, activeCityHub = null;", "let interiorState = null, interiorGroup = null, genericInteriorGroup = null, activeCityHub = null, buildingEntryPrompt = null;", 1)
text = text.replace("let weatherParticles, directionalLight, ambientLight, hemisphereLight, sandboxGround;", "let weatherParticles, cloudLayer = null, directionalLight, ambientLight, hemisphereLight, sandboxGround;", 1)
text = text.replace("const INTERIOR_ORIGIN = new THREE.Vector3(0, 0, -180);", "const INTERIOR_ORIGIN = new THREE.Vector3(0, 0, -180);\n        const GENERIC_INTERIOR_ORIGIN = new THREE.Vector3(0, 0, -240);", 1)
text = text.replace("visual: { pixelRatio: 2.0, shadows: true, shadowSize: 1536, shadowExtent: 52, shadowMs: 260, shadowDistance: 1.0, chunkBuildings: 17, chunkRadius: 3, weatherCount: 1450, npcCap: 180, npcStride: 1, mapMs: 85, hudMs: 100, weatherStride: 1 }", "visual: { pixelRatio: 2.0, shadows: true, shadowSize: 2048, shadowExtent: 58, shadowMs: 210, shadowDistance: 1.0, chunkBuildings: 19, chunkRadius: 3, weatherCount: 1800, npcCap: 180, npcStride: 1, mapMs: 85, hudMs: 100, weatherStride: 1 }", 1)

old_init_sky = '''        function initSky() {
            sky = new Sky();
            sky.scale.setScalar(8192);
            sky.material.uniforms['turbidity'].value = 7.5;
            sky.material.uniforms['rayleigh'].value = 1.85;
            sky.material.uniforms['mieCoefficient'].value = 0.005;
            sky.material.uniforms['mieDirectionalG'].value = 0.78;
            scene.background = new THREE.Color(0xa8ddff);
            scene.add(sky);
            sun = new THREE.Vector3();
        }'''
new_init_sky = '''        function initSky() {
            sky = new Sky(); sky.scale.setScalar(8192);
            sky.material.uniforms['turbidity'].value=7.5;sky.material.uniforms['rayleigh'].value=1.85;sky.material.uniforms['mieCoefficient'].value=.005;sky.material.uniforms['mieDirectionalG'].value=.78;
            scene.background=new THREE.Color(0xa8ddff);scene.add(sky);sun=new THREE.Vector3();createCloudLayer();
        }
        function createCloudLayer() {
            cloudLayer=new THREE.Group();cloudLayer.name='volumetric-cloud-layer';const cloudMat=new THREE.MeshStandardMaterial({color:0xf4fbff,roughness:.94,metalness:0,transparent:true,opacity:.52,depthWrite:false});const geo=new THREE.SphereGeometry(1,12,9);
            for(let i=0;i<15;i++){const cloud=new THREE.Group();const scale=7+hash2D(i,17,211)*10;for(let puff=0;puff<5;puff++){const mesh=new THREE.Mesh(geo,cloudMat);const a=puff/5*Math.PI*2;mesh.position.set(Math.cos(a)*scale*.38,(hash2D(i,puff,233)-.35)*scale*.16,Math.sin(a)*scale*.26);mesh.scale.set(scale*(.42+hash2D(i,puff,241)*.28),scale*(.15+hash2D(i,puff,251)*.14),scale*(.25+hash2D(i,puff,257)*.22));cloud.add(mesh);}cloud.position.set((hash2D(i,3,263)-.5)*150,28+hash2D(i,9,269)*22,(hash2D(i,7,271)-.5)*150);cloud.userData.phase=hash2D(i,11,277)*Math.PI*2;cloudLayer.add(cloud);}scene.add(cloudLayer);
        }
        function updateCloudLayer(time, focus) {
            if(!cloudLayer)return;cloudLayer.position.set(Math.floor(focus.x/96)*96,0,Math.floor(focus.z/96)*96);const weather=document.getElementById('weather-select')?.value||'sunny';const targetOpacity=weather==='sunny'?.28:weather==='cloudy'?.64:.78;cloudLayer.visible=qualityMode!=='performance'||weather!=='sunny';cloudLayer.children.forEach((cloud,index)=>{cloud.position.x+=Math.sin(time*.000018+cloud.userData.phase)*.012;cloud.position.z+=Math.cos(time*.000014+cloud.userData.phase)*.008;cloud.traverse(node=>{if(node.isMesh)node.material.opacity=targetOpacity*(qualityMode==='visual'?1:.76);});});
        }'''
if old_init_sky not in text: raise SystemExit('initSky block missing')
text = text.replace(old_init_sky, new_init_sky, 1)

new_assets = r'''        function createChunkAssets() {
            const loader=new THREE.TextureLoader();const facadeTexture=loader.load('assets/generated/urban-facade-atlas.png');facadeTexture.colorSpace=THREE.SRGBColorSpace;facadeTexture.wrapS=facadeTexture.wrapT=THREE.RepeatWrapping;facadeTexture.anisotropy=Math.min(8,renderer?.capabilities?.getMaxAnisotropy?.()||1);
            const groundMaterial=new THREE.MeshStandardMaterial({color:0x94bd83,roughness:.92,metalness:0});const roadMaterial=new THREE.MeshStandardMaterial({color:0x344451,roughness:.68,metalness:.16});buildingMaterial=new THREE.MeshStandardMaterial({color:0xffffff,vertexColors:true,roughness:.43,metalness:.16});const facadeMaterial=new THREE.MeshStandardMaterial({color:0xffffff,map:facadeTexture,roughness:.28,metalness:.28,emissive:0x183547,emissiveIntensity:.12});const entryMaterial=new THREE.MeshStandardMaterial({color:0x99edff,roughness:.14,metalness:.68,emissive:0x196f95,emissiveIntensity:.42});const barkMaterial=new THREE.MeshStandardMaterial({color:0x5b3825,roughness:.93,metalness:0});const leafMaterial=new THREE.MeshStandardMaterial({color:0x287b4a,roughness:.82,metalness:0});const leafLightMaterial=new THREE.MeshStandardMaterial({color:0x4fa96a,roughness:.74,metalness:0});
            return {groundGeometry:new THREE.PlaneGeometry(CHUNK_SIZE,CHUNK_SIZE),unitPlane:new THREE.PlaneGeometry(1,1),buildingGeometry:new THREE.BoxGeometry(1,1,1),facadeGeometry:new THREE.BoxGeometry(1,1,.05),roofGeometry:new THREE.BoxGeometry(1,1,1),entryGeometry:new THREE.BoxGeometry(1,1,.07),trunkGeometry:new THREE.CylinderGeometry(.18,.29,1,8),crownGeometry:new THREE.IcosahedronGeometry(1,1),groundMaterial,roadMaterial,buildingMaterial,facadeMaterial,entryMaterial,barkMaterial,leafMaterial,leafLightMaterial};
        }

'''
text = replace_between(text, '        function createChunkAssets() {', '        function chunkKey(', new_assets)

new_load_chunk = r'''        function loadChunk(cx, cz) {
            const origin=chunkOrigin(cx,cz),group=new THREE.Group();group.name='chunk-'+cx+'-'+cz;group.matrixAutoUpdate=false;group.updateMatrix();
            const ground=new THREE.Mesh(chunkAssets.groundGeometry,chunkAssets.groundMaterial);ground.rotation.x=-Math.PI/2;ground.position.set(origin.x+CHUNK_SIZE/2,0,origin.z+CHUNK_SIZE/2);ground.receiveShadow=true;ground.userData.chunkGround=true;group.add(ground);
            const roadLayouts=[];for(let worldX=Math.ceil(origin.x/ROAD_INTERVAL)*ROAD_INTERVAL;worldX<=origin.x+CHUNK_SIZE;worldX+=ROAD_INTERVAL)roadLayouts.push({x:worldX,z:origin.z+CHUNK_SIZE/2,sx:ROAD_WIDTH,sz:CHUNK_SIZE});for(let worldZ=Math.ceil(origin.z/ROAD_INTERVAL)*ROAD_INTERVAL;worldZ<=origin.z+CHUNK_SIZE;worldZ+=ROAD_INTERVAL)roadLayouts.push({x:origin.x+CHUNK_SIZE/2,z:worldZ,sx:CHUNK_SIZE,sz:ROAD_WIDTH});
            const helper=new THREE.Object3D(),roadMesh=new THREE.InstancedMesh(chunkAssets.unitPlane,chunkAssets.roadMaterial,roadLayouts.length);roadLayouts.forEach((road,index)=>{helper.position.set(road.x,.012,road.z);helper.rotation.set(-Math.PI/2,0,0);helper.scale.set(road.sx,road.sz,1);helper.updateMatrix();roadMesh.setMatrixAt(index,helper.matrix);});roadMesh.instanceMatrix.needsUpdate=true;roadMesh.receiveShadow=true;group.add(roadMesh);
            const specs=[],kinds=[{name:'RESIDENCE',height:[8,16],color:0xb8c8d4},{name:'COMMERCIAL',height:[10,20],color:0xc7b6a7},{name:'OFFICE',height:[20,36],color:0x93acc5},{name:'FACTORY',height:[7,13],color:0xa9a9a2},{name:'STATION',height:[8,15],color:0x9eb8ae},{name:'ATRIUM',height:[12,24],color:0xb7a8c1}];const attempts=qualityConfig().chunkBuildings*3;
            for(let index=0;index<attempts&&specs.length<qualityConfig().chunkBuildings;index++){const seed=hash2D(cx*101+index,cz*67-index,11),seed2=hash2D(cx*43-index,cz*97+index,29),x=origin.x+4+seed*(CHUNK_SIZE-8),z=origin.z+4+seed2*(CHUNK_SIZE-8),isHubLot=cx===0&&cz===0&&Math.abs(x-20)<9&&Math.abs(z-20)<9;if(isRoadCoordinate(x)||isRoadCoordinate(z)||isHubLot)continue;const kind=kinds[Math.floor(hash2D(cx+index,cz-index,337)*kinds.length)];const height=kind.height[0]+hash2D(cx+index,cz-index,53)*(kind.height[1]-kind.height[0]),size=4+hash2D(cx-index,cz+index,71)*4;const entrance=new THREE.Vector3(x,0,z-size/2-.45);specs.push({x,z,height,size,kind,color:new THREE.Color(kind.color).lerp(new THREE.Color(0xffffff),hash2D(cx,index,343)*.16),entrance,label:kind.name});}
            const buildingSurfaceMaterial=new THREE.MeshStandardMaterial({color:0xffffff,vertexColors:true,roughness:.42,metalness:.18,emissive:0x09151d,emissiveIntensity:.06});const buildingMesh=new THREE.InstancedMesh(chunkAssets.buildingGeometry,buildingSurfaceMaterial,Math.max(specs.length,1));specs.forEach((spec,index)=>{helper.rotation.set(0,0,0);helper.position.set(spec.x,spec.height/2,spec.z);helper.scale.set(spec.size,spec.height,spec.size);helper.updateMatrix();buildingMesh.setMatrixAt(index,helper.matrix);buildingMesh.setColorAt(index,spec.color);});buildingMesh.count=specs.length;buildingMesh.instanceMatrix.needsUpdate=true;buildingMesh.instanceColor.needsUpdate=true;buildingMesh.castShadow=false;buildingMesh.receiveShadow=true;buildingMesh.userData.dynamicShadowCaster=true;group.add(buildingMesh);
            const roofMaterial=new THREE.MeshStandardMaterial({color:0xe7eef3,roughness:.28,metalness:.3,emissive:0x173a50,emissiveIntensity:.12});const roofMesh=new THREE.InstancedMesh(chunkAssets.roofGeometry,roofMaterial,Math.max(specs.length,1));const roofUnits=new THREE.InstancedMesh(chunkAssets.roofGeometry,new THREE.MeshStandardMaterial({color:0x526979,roughness:.46,metalness:.36}),Math.max(specs.length,1));specs.forEach((spec,index)=>{helper.rotation.set(0,0,0);helper.position.set(spec.x,spec.height+.13,spec.z);helper.scale.set(spec.size*1.08,.26,spec.size*1.08);helper.updateMatrix();roofMesh.setMatrixAt(index,helper.matrix);helper.position.set(spec.x+spec.size*.16,spec.height+.52,spec.z);helper.scale.set(Math.max(.7,spec.size*.28),.55,Math.max(.7,spec.size*.28));helper.updateMatrix();roofUnits.setMatrixAt(index,helper.matrix);});roofMesh.count=roofUnits.count=specs.length;roofMesh.instanceMatrix.needsUpdate=true;roofUnits.instanceMatrix.needsUpdate=true;roofMesh.userData.dynamicShadowCaster=roofUnits.userData.dynamicShadowCaster=true;group.add(roofMesh,roofUnits);
            const facadeMesh=new THREE.InstancedMesh(chunkAssets.facadeGeometry,chunkAssets.facadeMaterial,Math.max(specs.length*12,1));let facadeIndex=0;const sides=[{axis:'z',sign:1},{axis:'z',sign:-1},{axis:'x',sign:1},{axis:'x',sign:-1}];specs.forEach(spec=>sides.forEach(side=>[-.31,0,.31].forEach(offset=>{helper.rotation.set(0,side.axis==='x'?Math.PI/2:0,0);if(side.axis==='z')helper.position.set(spec.x+offset*spec.size,spec.height*.54,spec.z+side.sign*(spec.size/2+.04));else helper.position.set(spec.x+side.sign*(spec.size/2+.04),spec.height*.54,spec.z+offset*spec.size);helper.scale.set(spec.size*.19,spec.height*.7,1);helper.updateMatrix();facadeMesh.setMatrixAt(facadeIndex++,helper.matrix);})));facadeMesh.count=facadeIndex;facadeMesh.instanceMatrix.needsUpdate=true;facadeMesh.userData.dynamicShadowCaster=true;group.add(facadeMesh);
            const entryMesh=new THREE.InstancedMesh(chunkAssets.entryGeometry,chunkAssets.entryMaterial,Math.max(specs.length,1));specs.forEach((spec,index)=>{helper.position.set(spec.entrance.x,1.35,spec.entrance.z+.1);helper.rotation.set(0,0,0);helper.scale.set(Math.min(2.3,spec.size*.38),2.7,1);helper.updateMatrix();entryMesh.setMatrixAt(index,helper.matrix);});entryMesh.count=specs.length;entryMesh.instanceMatrix.needsUpdate=true;entryMesh.userData.dynamicShadowCaster=true;group.add(entryMesh);
            const treeLocations=[];for(let index=0;index<9;index++){const x=origin.x+5+hash2D(cx+index,cz,151)*(CHUNK_SIZE-10),z=origin.z+5+hash2D(cx,cz-index,173)*(CHUNK_SIZE-10);if(!isRoadCoordinate(x)&&!isRoadCoordinate(z)&&!specs.some(spec=>Math.abs(spec.x-x)<spec.size&&Math.abs(spec.z-z)<spec.size))treeLocations.push({x,z,s:.75+hash2D(cx,cz,index)*.62});}
            if(treeLocations.length){const trunks=new THREE.InstancedMesh(chunkAssets.trunkGeometry,chunkAssets.barkMaterial,treeLocations.length),crowns=new THREE.InstancedMesh(chunkAssets.crownGeometry,chunkAssets.leafMaterial,treeLocations.length*3),highlights=new THREE.InstancedMesh(chunkAssets.crownGeometry,chunkAssets.leafLightMaterial,treeLocations.length*2);let crownIndex=0,lightIndex=0;treeLocations.forEach((tree,index)=>{helper.position.set(tree.x,1.2*tree.s,tree.z);helper.rotation.set(0,hash2D(cx,cz,index+191)*Math.PI*2,0);helper.scale.set(tree.s,2.4*tree.s,tree.s);helper.updateMatrix();trunks.setMatrixAt(index,helper.matrix);[[-.42,.35,.42],[.42,.42,.35],[0,.78,.52]].forEach((offset,j)=>{helper.position.set(tree.x+offset[0]*tree.s,2.25*tree.s+offset[1]*tree.s,tree.z+offset[2]*tree.s);helper.scale.set(1.15*tree.s,1.05*tree.s,1.05*tree.s);helper.updateMatrix();crowns.setMatrixAt(crownIndex++,helper.matrix);if(j<2){helper.position.y+=.22*tree.s;helper.scale.multiplyScalar(.72);helper.updateMatrix();highlights.setMatrixAt(lightIndex++,helper.matrix);}});});trunks.instanceMatrix.needsUpdate=true;crowns.instanceMatrix.needsUpdate=true;highlights.instanceMatrix.needsUpdate=true;[trunks,crowns,highlights].forEach(mesh=>{mesh.receiveShadow=true;mesh.userData.dynamicShadowCaster=true;});group.add(trunks,crowns,highlights);}
            const entries=specs.map(spec=>({position:spec.entrance.clone(),label:spec.label,spec,chunkKey:chunkKey(cx,cz),visible:true}));buildings.push(...entries);const colliders=specs.map(spec=>({minX:spec.x-spec.size*.53,maxX:spec.x+spec.size*.53,minZ:spec.z-spec.size*.53,maxZ:spec.z+spec.size*.53,kind:'building'}));let hub=null;if(cx===0&&cz===0){hub=createCityHubExterior(new THREE.Vector3(20,0,20));group.add(hub.group);colliders.push(...hub.colliders);activeCityHub=hub;}mapObjects.add(group);loadedChunks.set(chunkKey(cx,cz),{cx,cz,group,ground,specs,entries,colliders,hub});sandboxGround=ground;chunkLoadCount++;
        }

'''
text = replace_between(text, '        function loadChunk(cx, cz) {', '        function createCityHubExterior(', new_load_chunk)

old_unload = '''        function unloadChunk(key) {
            const chunk = loadedChunks.get(key);
            if (!chunk) return;
            mapObjects.remove(chunk.group);
            chunk.group.clear();
            if (renderer?.renderLists?.dispose) renderer.renderLists.dispose();
            loadedChunks.delete(key);
            chunkUnloadCount++;
        }'''
new_unload = '''        function unloadChunk(key) {
            const chunk=loadedChunks.get(key);if(!chunk)return;mapObjects.remove(chunk.group);if(chunk.entries?.length)buildings=buildings.filter(entry=>entry.chunkKey!==key);chunk.group.clear();if(renderer?.renderLists?.dispose)renderer.renderLists.dispose();loadedChunks.delete(key);chunkUnloadCount++;
        }'''
if old_unload not in text: raise SystemExit('unload block missing')
text = text.replace(old_unload, new_unload, 1)

new_interior = r'''        function createGenericInterior() {
            if(genericInteriorGroup)return genericInteriorGroup;const group=new THREE.Group();group.name='generic-building-interior';const floorMat=new THREE.MeshStandardMaterial({color:0x7c8790,roughness:.34,metalness:.28}),wallMat=new THREE.MeshStandardMaterial({color:0xd7e1e5,roughness:.54,metalness:.06}),woodMat=new THREE.MeshStandardMaterial({color:0x8b5f3d,roughness:.58,metalness:.05}),glowMat=new THREE.MeshStandardMaterial({color:0x76e8ff,roughness:.13,metalness:.35,emissive:0x157da6,emissiveIntensity:.65});const add=(geo,mat,x,y,z)=>{const mesh=new THREE.Mesh(geo,mat);mesh.position.set(GENERIC_INTERIOR_ORIGIN.x+x,y,GENERIC_INTERIOR_ORIGIN.z+z);mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.dynamicShadowCaster=true;group.add(mesh);return mesh;};add(new THREE.BoxGeometry(18,.28,18),floorMat,0,-.14,0);add(new THREE.BoxGeometry(18,6,.36),wallMat,0,3,-9);add(new THREE.BoxGeometry(18,6,.36),wallMat,0,3,9);add(new THREE.BoxGeometry(.36,6,18),wallMat,-9,3,0);add(new THREE.BoxGeometry(.36,6,18),wallMat,9,3,0);add(new THREE.BoxGeometry(5.6,1.15,1.4),woodMat,0,.58,-1.8);[-5.8,5.8].forEach(x=>{add(new THREE.BoxGeometry(2.3,2.1,.45),glowMat,x,2.4,-8.73);add(new THREE.BoxGeometry(2.8,.12,.14),glowMat,x,5.15,-8.68);});for(let i=-2;i<=2;i++)add(new THREE.BoxGeometry(1.3,.72,1.05),woodMat,i*2.7,.36,2.4);[-5,0,5].forEach(x=>{const lamp=new THREE.PointLight(0xffe1b0,.52,10,2);lamp.position.set(GENERIC_INTERIOR_ORIGIN.x+x,5.3,GENERIC_INTERIOR_ORIGIN.z-.5);group.add(lamp);});scene.add(group);genericInteriorGroup=group;return group;
        }
        function getNearestBuildingEntry(position) { const candidates=buildings.filter(entry=>entry.visible);return candidates.reduce((best,entry)=>{const distanceSq=entry.position.distanceToSquared(position);return(!best||distanceSq<best.distanceSq)?{entry,distanceSq}:best;},null); }
        function ensureBuildingEntryPrompt() { if(buildingEntryPrompt)return buildingEntryPrompt;const div=document.createElement('div');div.className='building-proximity';div.innerHTML='<b>E</b><span>建物に入る</span><small>BUILDING ENTRY</small>';buildingEntryPrompt=new CSS2DObject(div);buildingEntryPrompt.visible=false;scene.add(buildingEntryPrompt);return buildingEntryPrompt; }
        function updateInteractionPrompts() { const prompt=ensureBuildingEntryPrompt();if(interiorState||controlledVehicle||ridingTransit){prompt.visible=false;return;}const nearest=getNearestBuildingEntry(playerGroup.position);const hub=getNearestCityHub(playerGroup.position);const target=hub&&(!nearest||hub.distanceSq<nearest.distanceSq)?{position:hub.hub.entrance,label:'CITY HUB',distanceSq:hub.distanceSq}:{position:nearest?.entry.position,label:nearest?.entry.label,distanceSq:nearest?.distanceSq};if(target?.position&&target.distanceSq<7.4*7.4){prompt.position.copy(target.position).add(new THREE.Vector3(0,2.45,0));prompt.visible=true;prompt.element.innerHTML=`<b>E</b><span>${target.label} に入る</span><small>BUILDING ENTRY</small>`;labelRenderUntil=Math.max(labelRenderUntil,performance.now()+240);}else prompt.visible=false; }
        function tryEnterOrExitInterior() {
            if(interiorState){const origin=interiorState.origin;const exit=origin.clone().add(new THREE.Vector3(0,0,8.2));if(playerGroup.position.distanceToSquared(exit)>30){setSandboxMessage('出口ゲートに近づいて「使う」を押してください。');return true;}playerGroup.position.copy(interiorState.exitPosition.clone().add(new THREE.Vector3(0,0,-1.8)));interiorState=null;cameraOffsetSpherical.radius=Math.max(cameraOffsetSpherical.radius,8);updateChunkStreaming(playerGroup.position,true);setSandboxMessage('街の外へ戻りました。');return true;}
            if(controlledVehicle||ridingTransit){setSandboxMessage('建物へ入る前に乗り物を降りてください。');return true;}const hub=getNearestCityHub(playerGroup.position);const building=getNearestBuildingEntry(playerGroup.position);const useHub=hub&&(!building||hub.distanceSq<building.distanceSq);if(!useHub&&(!building||building.distanceSq>7.4*7.4))return false;
            if(useHub){ensureCityHubInterior();interiorState={kind:'hub',origin:INTERIOR_ORIGIN,exitPosition:hub.hub.entrance.clone(),colliders:[{minX:INTERIOR_ORIGIN.x-10,maxX:INTERIOR_ORIGIN.x+10,minZ:INTERIOR_ORIGIN.z-10,maxZ:INTERIOR_ORIGIN.z-9.45,kind:'interior-wall'},{minX:INTERIOR_ORIGIN.x-10,maxX:INTERIOR_ORIGIN.x+10,minZ:INTERIOR_ORIGIN.z+9.45,maxZ:INTERIOR_ORIGIN.z+10,kind:'interior-wall'},{minX:INTERIOR_ORIGIN.x-10,maxX:INTERIOR_ORIGIN.x-9.45,minZ:INTERIOR_ORIGIN.z-10,maxZ:INTERIOR_ORIGIN.z+10,kind:'interior-wall'},{minX:INTERIOR_ORIGIN.x+9.45,maxX:INTERIOR_ORIGIN.x+10,minZ:INTERIOR_ORIGIN.z-10,maxZ:INTERIOR_ORIGIN.z+10,kind:'interior-wall'},{minX:INTERIOR_ORIGIN.x-2.8,maxX:INTERIOR_ORIGIN.x+2.8,minZ:INTERIOR_ORIGIN.z-2.8,maxZ:INTERIOR_ORIGIN.z-1.1,kind:'interior-desk'}]};playerGroup.position.copy(INTERIOR_ORIGIN.clone().add(new THREE.Vector3(0,0,6.4)));playerGroup.rotation.y=Math.PI;cameraOffsetSpherical.radius=Math.min(cameraOffsetSpherical.radius,5.2);cameraOffsetSpherical.theta=Math.PI;setSandboxMessage('City Hubへ入館しました。出口ゲートで「使う」を押すと街へ戻れます。');return true;}
            createGenericInterior();const o=GENERIC_INTERIOR_ORIGIN;interiorState={kind:'building',origin:o,exitPosition:building.entry.position.clone(),label:building.entry.label,colliders:[{minX:o.x-9,maxX:o.x+9,minZ:o.z-9,maxZ:o.z-8.6,kind:'interior-wall'},{minX:o.x-9,maxX:o.x+9,minZ:o.z+8.6,maxZ:o.z+9,kind:'interior-wall'},{minX:o.x-9,maxX:o.x-8.6,minZ:o.z-9,maxZ:o.z+9,kind:'interior-wall'},{minX:o.x+8.6,maxX:o.x+9,minZ:o.z-9,maxZ:o.z+9,kind:'interior-wall'},{minX:o.x-2.9,maxX:o.x+2.9,minZ:o.z-2.5,maxZ:o.z-.8,kind:'interior-counter'}]};playerGroup.position.copy(o.clone().add(new THREE.Vector3(0,0,6.2)));playerGroup.rotation.y=Math.PI;cameraOffsetSpherical.radius=Math.min(cameraOffsetSpherical.radius,5.2);cameraOffsetSpherical.theta=Math.PI;setSandboxMessage(`${building.entry.label}へ入りました。出口ゲートで「使う」を押すと街へ戻れます。`);return true;
        }

'''
text = replace_between(text, '        function tryEnterOrExitInterior() {', '        function unloadChunk(', new_interior)

new_weather = r'''        function changeWeather(weather) {
            if(weatherParticles){scene.remove(weatherParticles);weatherParticles.geometry.dispose();weatherParticles.material.dispose();weatherParticles=null;}updateTime(parseFloat(document.getElementById('time-slider').value));const uniforms=sky.material.uniforms;if(weather==='cloudy'){uniforms['turbidity'].value=13;uniforms['rayleigh'].value=.9;}else if(weather==='rainy'||weather==='snowy'){uniforms['turbidity'].value=18;uniforms['rayleigh'].value=.42;const count=weather==='rainy'?qualityConfig().weatherCount:Math.floor(qualityConfig().weatherCount*.65),positions=new Float32Array(count*3),velocities=new Float32Array(count*3),geometry=new THREE.BufferGeometry();for(let i=0;i<count*3;i+=3){positions[i]=(Math.random()-.5)*110;positions[i+1]=Math.random()*48;positions[i+2]=(Math.random()-.5)*110;velocities[i]=weather==='snowy'?(Math.random()-.5)*.05:0;velocities[i+1]=weather==='rainy'?-Math.random()*.8-.5:-Math.random()*.05-.02;}geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('velocity',new THREE.BufferAttribute(velocities,3));const material=new THREE.PointsMaterial({color:weather==='rainy'?0xa8bad4:0xffffff,size:weather==='rainy'?.045:.15,transparent:true,opacity:weather==='rainy'?.65:.72,sizeAttenuation:true});weatherParticles=new THREE.Points(geometry,material);scene.add(weatherParticles);}if(cloudLayer)cloudLayer.visible=weather!=='sunny'||qualityMode==='visual';
        }

'''
text = replace_between(text, '        function changeWeather(weather) {', '        function drawMapBackground()', new_weather)

text = text.replace("directionalLight.shadow.bias = qualityMode === 'visual' ? -0.00045 : -0.00035;\n            directionalLight.shadow.normalBias = qualityMode === 'visual' ? 0.045 : 0.035;", "directionalLight.shadow.bias = qualityMode === 'visual' ? -0.00016 : -0.00024;\n            directionalLight.shadow.normalBias = qualityMode === 'visual' ? 0.018 : 0.026;", 1)
text = text.replace("            updateVehicleUi();\n            handleNpcChat(time);", "            updateVehicleUi();\n            updateInteractionPrompts();\n            updateCloudLayer(time, controlledObject.position);\n            handleNpcChat(time);", 1)

path.write_text(text)
print('Applied phase 6 city quality refresh')
