from pathlib import Path

path = Path('/home/ubuntu/Ultimate-3D-Game/index.html')
text = path.read_text()

css = r'''
        /* Mega refresh: full-screen navigation, guide, and City Atlas. */
        #pause-screen { position:fixed !important; inset:0 !important; z-index:10000 !important; isolation:isolate; overflow:hidden; }
        #pause-screen .pause-hub { position:relative; width:100%; min-height:100%; grid-template-columns:minmax(300px,.82fr) minmax(500px,1.18fr); background:radial-gradient(circle at 80% 12%,rgba(94,179,255,.25),transparent 28%),linear-gradient(135deg,#061b3c,#0c4e91 58%,#08224a); }
        .pause-hub::after { position:absolute; right:clamp(24px,5vw,90px); bottom:clamp(22px,4vw,66px); width:min(38vw,500px); height:min(38vw,500px); border:1px solid rgba(145,218,255,.18); border-radius:50%; box-shadow:0 0 0 34px rgba(145,218,255,.04),0 0 0 68px rgba(145,218,255,.025); content:''; pointer-events:none; }
        .pause-hub-intro,.pause-hub-actions { position:relative; z-index:1; } .pause-hub-actions { max-width:800px; }
        .pause-hub-button { min-height:104px; background:linear-gradient(160deg,rgba(255,255,255,.98),rgba(232,246,255,.96)); }
        .pause-hub-button.primary { background:linear-gradient(145deg,#5ebdff,#2176eb); } .pause-hub-button.map { background:linear-gradient(145deg,#e8fbff,#d4f1ff); border-color:#7bcaf5; }
        .full-ui-screen { position:fixed; inset:0; z-index:10001; display:flex; color:#eef9ff; background:radial-gradient(circle at 84% 10%,rgba(42,154,255,.29),transparent 30%),radial-gradient(circle at 12% 92%,rgba(50,224,174,.15),transparent 34%),linear-gradient(135deg,#041731,#0a467f); overflow:hidden; }
        .full-ui-screen.hidden { visibility:hidden; opacity:0; pointer-events:none; } .full-ui-close { position:absolute; z-index:4; top:calc(16px + env(safe-area-inset-top)); right:calc(16px + env(safe-area-inset-right)); width:48px; height:48px; display:grid; place-items:center; border:2px solid rgba(255,255,255,.72); border-radius:16px; color:white; background:rgba(255,255,255,.12); font-size:24px; font-weight:800; }
        .guide-shell,.atlas-shell { width:100%; min-height:100%; display:grid; grid-template-columns:minmax(270px,.72fr) minmax(500px,1.28fr); gap:clamp(24px,4vw,70px); align-items:center; padding:clamp(28px,6vw,90px); overflow:auto; }
        .screen-kicker { display:inline-flex; align-items:center; gap:8px; color:#99dfff; font-size:10px; font-weight:900; letter-spacing:.18em; } .screen-kicker::before { width:8px; height:8px; border-radius:99px; background:#5ce6a7; box-shadow:0 0 16px #5ce6a7; content:''; }
        .guide-intro h2,.atlas-intro h2 { margin:12px 0; font-size:clamp(40px,5.6vw,76px); line-height:.9; letter-spacing:-.07em; } .guide-intro h2 em,.atlas-intro h2 em { display:block; color:#7ed7ff; font-style:normal; } .guide-intro p,.atlas-intro p { max-width:450px; color:#c8eaff; font-size:14px; font-weight:650; line-height:1.7; }
        .guide-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:12px; max-width:850px; } .guide-card { min-height:180px; padding:18px; border:2px solid rgba(255,255,255,.82); border-radius:21px; color:#1f537f; background:rgba(250,254,255,.97); box-shadow:0 8px 0 rgba(0,30,70,.22),0 18px 34px rgba(0,12,40,.2); } .guide-card h3 { display:flex; align-items:center; gap:8px; margin:0 0 11px; color:#23629d; font-size:12px; letter-spacing:.05em; } .guide-card p { margin:7px 0; color:#4d7296; font-size:11px; font-weight:700; line-height:1.55; } .guide-card kbd { display:inline-grid; min-width:25px; place-items:center; padding:2px 5px; border:1px solid #b9d8ef; border-radius:6px; color:#1d609b; background:#eef8ff; font:800 10px Inter,sans-serif; }
        .guide-foot { grid-column:1/-1; display:flex; justify-content:flex-end; } .screen-primary { display:inline-flex; min-height:52px; align-items:center; justify-content:center; gap:8px; padding:0 20px; border:2px solid #a8d9ff; border-radius:15px; color:white; background:linear-gradient(180deg,#5aaeff,#2070df); box-shadow:0 5px 0 rgba(2,41,92,.36); font-weight:900; }
        .atlas-shell { grid-template-columns:minmax(240px,.55fr) minmax(540px,1.45fr); } .atlas-intro { align-self:start; padding-top:clamp(36px,8vh,100px); } .atlas-legend { display:grid; gap:8px; margin-top:20px; } .atlas-legend span { display:flex; align-items:center; gap:8px; color:#dff3ff; font-size:11px; font-weight:800; } .atlas-dot { width:10px; height:10px; border-radius:50%; background:#fff; box-shadow:0 0 12px currentColor; } .atlas-dot.route{color:#49d9ff;background:#49d9ff}.atlas-dot.destination{color:#ff856f;background:#ff856f}.atlas-dot.npc{color:#b0e8ff;background:#b0e8ff}.atlas-dot.transit{color:#ffd26a;background:#ffd26a}
        .atlas-workbench { display:grid; grid-template-rows:auto minmax(300px,1fr) auto; gap:13px; min-height:min(78vh,820px); } .atlas-toolbar,.atlas-footer { display:flex; flex-wrap:wrap; align-items:center; gap:8px; } .atlas-chip { display:inline-flex; align-items:center; gap:6px; min-height:38px; padding:0 11px; border:1px solid rgba(255,255,255,.34); border-radius:11px; color:#dff4ff; background:rgba(255,255,255,.10); font-size:10px; font-weight:850; } .atlas-chip input { accent-color:#4cd9ff; } .atlas-tool { min-height:38px; padding:0 12px; border:1px solid rgba(255,255,255,.45); border-radius:11px; color:#e9f8ff; background:rgba(10,66,120,.72); font-size:11px; font-weight:900; } .atlas-tool.active { color:#113e68; background:#8bdcff; }
        .atlas-map-frame { position:relative; min-height:0; border:3px solid rgba(255,255,255,.85); border-radius:26px; overflow:hidden; background:linear-gradient(145deg,#0b2c56,#071a35); box-shadow:0 12px 0 rgba(0,24,56,.25),0 25px 48px rgba(0,0,0,.24); } #city-atlas-canvas { display:block; width:100%; height:100%; min-height:430px; touch-action:none; cursor:crosshair; } .atlas-map-label { position:absolute; top:14px; left:16px; padding:7px 10px; border:1px solid rgba(189,235,255,.28); border-radius:10px; color:#dcf6ff; background:rgba(4,25,53,.72); font-size:10px; font-weight:900; letter-spacing:.1em; pointer-events:none; } .atlas-coordinate { margin-left:auto; color:#b4e9ff; font-size:10px; font-weight:850; }
        #city-desk-button { position:absolute; z-index:34; top:76px; right:16px; display:inline-flex; min-height:42px; align-items:center; gap:7px; padding:0 12px; border:2px solid rgba(255,255,255,.8); border-radius:14px; color:#164a7d; background:rgba(250,254,255,.95); box-shadow:0 5px 0 rgba(7,54,116,.16),0 10px 22px rgba(7,35,70,.18); font-size:10px; font-weight:900; } body.drawer-open #city-desk-button { opacity:0; pointer-events:none; transform:translateX(12px); }
        .ui-container { z-index:33; } #map-container { z-index:27; width:156px; height:156px; right:18px; bottom:20px; } #map-container::before { content:'CITY RADAR · TAP FOR ATLAS'; font-size:8px; } #map-canvas { touch-action:manipulation; }
        #world-readout { z-index:27; width:min(284px,calc(100vw - 28px)); } #world-readout .readout-row { grid-template-columns:1fr 1fr; } #world-readout strong { overflow-wrap:anywhere; font-size:10px; } #world-readout #coords { letter-spacing:-.025em; }
        @media (pointer:coarse),(max-width:760px) { #pause-screen .pause-hub { grid-template-columns:1fr; align-content:start; gap:18px; overflow:auto; padding:72px 16px max(26px,env(safe-area-inset-bottom)); } .pause-hub-intro h2 { font-size:clamp(36px,12vw,54px); } .pause-hub-actions { grid-template-columns:1fr; } .pause-hub-button { min-height:78px; } .guide-shell,.atlas-shell { grid-template-columns:1fr; align-content:start; gap:18px; padding:70px 14px max(26px,env(safe-area-inset-bottom)); } .guide-intro h2,.atlas-intro h2 { font-size:clamp(38px,13vw,56px); } .guide-grid { grid-template-columns:1fr; } .guide-card { min-height:0; } .atlas-intro { padding-top:0; } .atlas-workbench { min-height:590px; } #city-atlas-canvas { min-height:360px; } .atlas-toolbar { gap:6px; } .atlas-chip { min-height:34px; padding:0 8px; font-size:9px; } .atlas-tool { min-height:36px; padding:0 9px; } #city-desk-button { top:calc(58px + env(safe-area-inset-top)); right:calc(8px + env(safe-area-inset-right)); } #map-container { right:calc(8px + env(safe-area-inset-right)); bottom:calc(142px + env(safe-area-inset-bottom)); width:130px; height:130px; } #world-readout { top:calc(58px + env(safe-area-inset-top)); left:calc(8px + env(safe-area-inset-left)); width:170px; } #world-readout .readout-row { grid-template-columns:1fr; gap:4px; } #world-readout .readout-chip:nth-child(2) { display:none; } }
'''
if 'Mega refresh: full-screen navigation' not in text:
    text = text.replace('        </style>', css + '\n        </style>', 1)

text = text.replace('''                <button id="pause-world-button" class="pause-hub-button"><svg class="bi-icon" aria-hidden="true"><use href="assets/bootstrap-icons.svg#globe2"></use></svg><span><strong>ワールド設定</strong><small>品質・天候・描画距離</small></span></button>''','''                <button id="pause-world-button" class="pause-hub-button"><svg class="bi-icon" aria-hidden="true"><use href="assets/bootstrap-icons.svg#globe2"></use></svg><span><strong>ワールド設定</strong><small>品質・天候・描画距離</small></span></button>
                <button id="pause-map-button" class="pause-hub-button map"><svg class="bi-icon" aria-hidden="true"><use href="assets/bootstrap-icons.svg#map-fill"></use></svg><span><strong>City Atlas</strong><small>目的地・交通・自動運転</small></span></button>''',1)

screens = r'''
    <section id="guide-screen" class="full-ui-screen hidden" role="dialog" aria-modal="true" aria-label="操作ガイド">
        <button id="guide-close" class="full-ui-close" type="button" aria-label="ガイドを閉じる">×</button>
        <div class="guide-shell"><div class="guide-intro"><div class="screen-kicker">INTERACTION ATLAS</div><h2>MOVE.<em>MAKE.</em>EXPLORE.</h2><p>キーボードとタッチのどちらでも、同じ街のすべての主要機能へ到達できます。近くの対象には「使う」または <b>E</b> のプロンプトが表示されます。</p></div><div class="guide-grid">
            <article class="guide-card"><h3><svg class="bi-icon"><use href="assets/bootstrap-icons.svg#person-walking"></use></svg>MOVE & LOOK</h3><p><kbd>WASD</kbd> / 矢印キー またはジョイスティックで移動。</p><p><kbd>Shift</kbd> または走るボタンで加速。ドラッグ／スワイプで視点操作。</p></article>
            <article class="guide-card"><h3><svg class="bi-icon"><use href="assets/bootstrap-icons.svg#car-front-fill"></use></svg>VEHICLES & TRANSIT</h3><p>車両・建物・NPCの近くで <kbd>E</kbd> または「使う」。</p><p>City Atlasで目的地を置き、徒歩または車の自動運転を開始できます。</p></article>
            <article class="guide-card"><h3><svg class="bi-icon"><use href="assets/bootstrap-icons.svg#box-seam-fill"></use></svg>BUILD BELT</h3><p><kbd>1–5</kbd> で素材、<kbd>B</kbd> で建築、<kbd>R</kbd> で回転、<kbd>7</kbd> で削除。</p><p>タッチではBuild Belt・Field Pack・建築ボタンで同じ操作を行います。</p></article>
            <article class="guide-card"><h3><svg class="bi-icon"><use href="assets/bootstrap-icons.svg#camera-reels-fill"></use></svg>CAMERA & MAP</h3><p>視点ボタンで三人称、第一人称、Free Camを切替。</p><p>マップはCity Atlasで拡大、パン、レイヤー表示、目的地設定ができます。</p></article>
            <article class="guide-card"><h3><svg class="bi-icon"><use href="assets/bootstrap-icons.svg#chat-square-text-fill"></use></svg>NPC & LOCAL AI</h3><p>会話ドックでは街の会話を確認。NPCに近づくと個別会話を開けます。</p><p>LOCAL AIは明示的に開始したときだけ端末上へ読み込まれます。</p></article>
            <article class="guide-card"><h3><svg class="bi-icon"><use href="assets/bootstrap-icons.svg#gear-fill"></use></svg>FULL-SCREEN HUBS</h3><p><kbd>Esc</kbd> / <kbd>P</kbd> またはポーズでCity Pauseを開きます。</p><p>ガイド、地図、設定はすべて全画面で表示され、探索中のHUDを覆います。</p></article>
            <div class="guide-foot"><button id="guide-back" class="screen-primary" type="button"><svg class="bi-icon"><use href="assets/bootstrap-icons.svg#play-fill"></use></svg>ゲームへ戻る</button></div>
        </div></div>
    </section>
    <section id="city-atlas-screen" class="full-ui-screen hidden" role="dialog" aria-modal="true" aria-label="City Atlas">
        <button id="atlas-close" class="full-ui-close" type="button" aria-label="地図を閉じる">×</button>
        <div class="atlas-shell"><div class="atlas-intro"><div class="screen-kicker">CITY ATLAS</div><h2>SEE THE<em>WHOLE CITY.</em></h2><p>高解像度の都市地図で道路、建物、交通、NPC、目的地を確認できます。地図をタップまたはクリックして目的地を置き、徒歩または乗車中の自動運転を開始できます。</p><div class="atlas-legend"><span><i class="atlas-dot"></i>現在地・操作中の車両</span><span><i class="atlas-dot route"></i>経路</span><span><i class="atlas-dot destination"></i>目的地</span><span><i class="atlas-dot npc"></i>NPC</span><span><i class="atlas-dot transit"></i>公共交通・交通車両</span></div></div>
        <div class="atlas-workbench"><div class="atlas-toolbar"><button id="atlas-zoom-out" class="atlas-tool" type="button">－ 縮小</button><button id="atlas-zoom-in" class="atlas-tool" type="button">＋ 拡大</button><button id="atlas-recenter" class="atlas-tool active" type="button">現在地へ</button><label class="atlas-chip"><input id="atlas-teleport" type="checkbox">テレポート</label><label class="atlas-chip"><input id="atlas-layer-npcs" type="checkbox" checked>NPC</label><label class="atlas-chip"><input id="atlas-layer-transit" type="checkbox" checked>交通</label><span id="atlas-zoom-label" class="atlas-coordinate">ZOOM 1.0×</span></div>
        <div class="atlas-map-frame"><div class="atlas-map-label">LIVE CITY MAP · DRAG TO PAN · TAP TO PLACE</div><canvas id="city-atlas-canvas" width="1024" height="1024"></canvas></div>
        <div class="atlas-footer"><span id="atlas-destination-readout" class="atlas-chip">目的地を選択してください</span><button id="atlas-autodrive" class="screen-primary" type="button"><svg class="bi-icon"><use href="assets/bootstrap-icons.svg#sign-turn-right-fill"></use></svg>自動運転を開始</button><button id="atlas-back" class="atlas-tool" type="button">ゲームへ戻る</button></div></div></div>
    </section>
'''
if 'id="guide-screen"' not in text:
    text = text.replace('    <header id="game-topbar"', screens + '    <header id="game-topbar"', 1)

text = text.replace('''<div class="top-actions"><button id="drawer-toggle" class="round-button"><svg class="bi-icon" aria-hidden="true"><use href="assets/bootstrap-icons.svg#list"></use></svg><span class="button-label">メニュー</span></button><button id="pause-button" class="round-button primary"><svg class="bi-icon" aria-hidden="true"><use href="assets/bootstrap-icons.svg#pause-fill"></use></svg><span class="button-label">ポーズ</span></button></div>''','''<div class="top-actions"><button id="drawer-toggle" class="round-button"><svg class="bi-icon" aria-hidden="true"><use href="assets/bootstrap-icons.svg#list"></use></svg><span class="button-label">メニュー</span></button><button id="pause-button" class="round-button primary"><svg class="bi-icon" aria-hidden="true"><use href="assets/bootstrap-icons.svg#pause-fill"></use></svg><span class="button-label">ポーズ</span></button></div><button id="city-desk-button" type="button"><svg class="bi-icon" aria-hidden="true"><use href="assets/bootstrap-icons.svg#grid-1x2-fill"></use></svg>CITY DESK</button>''',1)

js = r'''
        let cityAtlasCanvas = null, cityAtlasCtx = null, cityAtlasZoom = 1.0, cityAtlasCenter = null, cityAtlasDragging = false, cityAtlasDragStart = null;
        function isMegaScreenOpen() { return ['guide-screen','city-atlas-screen','world-settings-screen'].some(id => !document.getElementById(id)?.classList.contains('hidden')); }
        function openMegaScreen(id) { if (!gameStarted) return; setPaused(true); document.getElementById('pause-screen').classList.add('hidden'); document.getElementById(id).classList.remove('hidden'); duckBgm(true); }
        function closeMegaScreen(id) { document.getElementById(id).classList.add('hidden'); duckBgm(false); setPaused(false); playBgm(); }
        function openGuide() { openMegaScreen('guide-screen'); }
        function closeGuide() { closeMegaScreen('guide-screen'); }
        function openCityAtlas() { openMegaScreen('city-atlas-screen'); const center = getControlledObject().position; cityAtlasCenter = new THREE.Vector3(center.x, 0, center.z); cityAtlasZoom = Math.max(.7, cityAtlasZoom); drawCityAtlas(); }
        function closeCityAtlas() { closeMegaScreen('city-atlas-screen'); }
        function atlasRange() { return Math.max(CHUNK_SIZE * .85, CHUNK_SIZE * 7 / cityAtlasZoom); }
        function atlasWorldToPixel(position) { const range = atlasRange(); return { x:(position.x - cityAtlasCenter.x) / range * cityAtlasCanvas.width + cityAtlasCanvas.width / 2, y:(position.z - cityAtlasCenter.z) / range * cityAtlasCanvas.height + cityAtlasCanvas.height / 2 }; }
        function drawCityAtlas() {
            if (!cityAtlasCanvas || document.getElementById('city-atlas-screen').classList.contains('hidden')) return;
            const ctx = cityAtlasCtx, w = cityAtlasCanvas.width, h = cityAtlasCanvas.height, range = atlasRange();
            ctx.clearRect(0,0,w,h); const grd=ctx.createLinearGradient(0,0,w,h); grd.addColorStop(0,'#0d3967'); grd.addColorStop(1,'#081b37'); ctx.fillStyle=grd; ctx.fillRect(0,0,w,h);
            const scale = w / range; const roadStartX = Math.floor((cityAtlasCenter.x-range/2)/ROAD_INTERVAL)*ROAD_INTERVAL; const roadStartZ = Math.floor((cityAtlasCenter.z-range/2)/ROAD_INTERVAL)*ROAD_INTERVAL;
            loadedChunks.forEach(chunk=>{ const origin=chunkOrigin(chunk.cx,chunk.cz); const p=atlasWorldToPixel(origin); const s=CHUNK_SIZE*scale; ctx.fillStyle='rgba(79,160,205,.15)';ctx.fillRect(p.x,p.y,s,s);ctx.strokeStyle='rgba(126,213,255,.22)';ctx.lineWidth=2;ctx.strokeRect(p.x,p.y,s,s); });
            ctx.strokeStyle='rgba(222,239,249,.52)'; ctx.lineWidth=Math.max(5,ROAD_WIDTH*scale); for(let x=roadStartX;x<=cityAtlasCenter.x+range/2;x+=ROAD_INTERVAL){const p=atlasWorldToPixel(new THREE.Vector3(x,0,cityAtlasCenter.z));ctx.beginPath();ctx.moveTo(p.x,0);ctx.lineTo(p.x,h);ctx.stroke();} for(let z=roadStartZ;z<=cityAtlasCenter.z+range/2;z+=ROAD_INTERVAL){const p=atlasWorldToPixel(new THREE.Vector3(cityAtlasCenter.x,0,z));ctx.beginPath();ctx.moveTo(0,p.y);ctx.lineTo(w,p.y);ctx.stroke();}
            buildings.forEach(b=>{ if(!b.visible) return; const p=atlasWorldToPixel(b.position); if(p.x<-18||p.x>w+18||p.y<-18||p.y>h+18)return; ctx.fillStyle='rgba(149,202,227,.45)';ctx.fillRect(p.x-7,p.y-7,14,14); });
            if (document.getElementById('atlas-layer-npcs').checked) { ctx.fillStyle='#bdeeff';npcs.forEach(n=>{const p=atlasWorldToPixel(n.position);ctx.fillRect(p.x-3,p.y-3,6,6);}); }
            if (document.getElementById('atlas-layer-transit').checked) { trafficVehicles.forEach(v=>{const p=atlasWorldToPixel(v.position);ctx.fillStyle=v.userData?.transit?'#ffdc6d':'#f2a45f';ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill();}); }
            if(path.length>1){ctx.strokeStyle=isAutoDriving?'#58e7ff':'#ff8a70';ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();let p=atlasWorldToPixel(path[0]);ctx.moveTo(p.x,p.y);for(let i=1;i<path.length;i++){p=atlasWorldToPixel(path[i]);ctx.lineTo(p.x,p.y);}ctx.stroke();}
            if(destination){const p=atlasWorldToPixel(destination);ctx.fillStyle='#ff806b';ctx.beginPath();ctx.arc(p.x,p.y,13,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();}
            const actor=getControlledObject(); const p=atlasWorldToPixel(actor.position);ctx.fillStyle='#ffffff';ctx.beginPath();ctx.arc(p.x,p.y,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1d9dea';ctx.beginPath();ctx.arc(p.x,p.y,6,0,Math.PI*2);ctx.fill();
            ctx.fillStyle='rgba(220,247,255,.9)';ctx.font='700 24px system-ui';ctx.fillText(`RANGE ±${Math.round(range/2)}m`,20,h-24);document.getElementById('atlas-zoom-label').textContent=`ZOOM ${cityAtlasZoom.toFixed(1)}× · ${Math.round(range)}m`;
            document.getElementById('atlas-destination-readout').textContent=destination?`目的地 X:${destination.x.toFixed(0)} Z:${destination.z.toFixed(0)} · ${path.length} points`:'目的地を選択してください';
        }
        function atlasPointerToWorld(event) { const rect=cityAtlasCanvas.getBoundingClientRect(); const x=(event.clientX-rect.left)/rect.width*cityAtlasCanvas.width;const y=(event.clientY-rect.top)/rect.height*cityAtlasCanvas.height;const range=atlasRange();return new THREE.Vector3(cityAtlasCenter.x+(x/cityAtlasCanvas.width-.5)*range,0,cityAtlasCenter.z+(y/cityAtlasCanvas.height-.5)*range); }
        function setAtlasDestination(event) { const point=atlasPointerToWorld(event); if(document.getElementById('atlas-teleport').checked){ playerGroup.position.copy(point);if(controlledVehicle)controlledVehicle.position.copy(point);updateChunkStreaming(point,true);destination=null;path=[];stopAutoDrive();setSandboxMessage('City Atlasからテレポートしました。'); } else { destination=point; path=findPath(getControlledObject().position,destination); stopAutoDrive(); setSandboxMessage(path.length?'目的地を設定しました。City Atlasから自動運転を開始できます。':'目的地への経路を作成できませんでした。'); } drawCityAtlas(); }
        function setupMegaUi() {
            cityAtlasCanvas=document.getElementById('city-atlas-canvas');cityAtlasCtx=cityAtlasCanvas.getContext('2d');
            const capture=(id,fn)=>document.getElementById(id).addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();fn();},true);
            capture('title-help-button',openGuide);capture('pause-help-button',openGuide);capture('help-button',openGuide);capture('quick-map',openCityAtlas);capture('pause-map-button',openCityAtlas);
            capture('guide-close',closeGuide);capture('guide-back',closeGuide);capture('atlas-close',closeCityAtlas);capture('atlas-back',closeCityAtlas);capture('city-desk-button',()=>toggleDrawer(true));
            document.getElementById('atlas-zoom-in').addEventListener('click',()=>{cityAtlasZoom=Math.min(5,cityAtlasZoom*1.25);drawCityAtlas();});
            document.getElementById('atlas-zoom-out').addEventListener('click',()=>{cityAtlasZoom=Math.max(.55,cityAtlasZoom/1.25);drawCityAtlas();});
            document.getElementById('atlas-recenter').addEventListener('click',()=>{const p=getControlledObject().position;cityAtlasCenter.set(p.x,0,p.z);drawCityAtlas();});
            document.getElementById('atlas-autodrive').addEventListener('click',()=>{if(!path.length){setSandboxMessage('先にCity Atlasで目的地を選択してください。');return;} startAutoDrive();closeCityAtlas();});
            ['atlas-layer-npcs','atlas-layer-transit','atlas-teleport'].forEach(id=>document.getElementById(id).addEventListener('change',drawCityAtlas));
            cityAtlasCanvas.addEventListener('pointerdown',e=>{cityAtlasDragging=true;cityAtlasDragStart={x:e.clientX,y:e.clientY,cx:cityAtlasCenter.x,cz:cityAtlasCenter.z};cityAtlasCanvas.setPointerCapture?.(e.pointerId);});
            cityAtlasCanvas.addEventListener('pointermove',e=>{if(!cityAtlasDragging)return;const rect=cityAtlasCanvas.getBoundingClientRect();const range=atlasRange();const dx=e.clientX-cityAtlasDragStart.x,dy=e.clientY-cityAtlasDragStart.y;if(Math.hypot(dx,dy)>8){cityAtlasCenter.x=cityAtlasDragStart.cx-dx/rect.width*range;cityAtlasCenter.z=cityAtlasDragStart.cz-dy/rect.height*range;drawCityAtlas();}});
            cityAtlasCanvas.addEventListener('pointerup',e=>{const d=Math.hypot(e.clientX-cityAtlasDragStart.x,e.clientY-cityAtlasDragStart.y);cityAtlasDragging=false;if(d<8)setAtlasDestination(e);});
        }

'''
if 'function setupMegaUi()' not in text:
    text = text.replace('        function startGame() {', js + '        function startGame() {', 1)

text = text.replace('            setupEventListeners();\n\n            createCityMap();', '            setupEventListeners();\n            setupMegaUi();\n\n            createCityMap();', 1)
text = text.replace("            document.getElementById('pause-help-button').addEventListener('click', () => { document.getElementById('help-modal').style.display = 'block'; });", "            document.getElementById('pause-help-button').addEventListener('click', () => { document.getElementById('help-modal').style.display = 'block'; });", 1)
path.write_text(text)
print('Applied fullscreen guide, City Atlas, and City Desk')
